version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: react-front-dev
    container_name: front-dev
    expose:
      - '3000'
    ports:
      - 3000:3000
    volumes:
      - ./:/app
