version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    env_file: .env
    expose:
      - '3000'
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - mysql

volumes:
  db-data:
