version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-host
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DB_PORT
    volumes:
      - db-data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-host
    env_file: .env
    restart: on-failure
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./src:/app/src
    depends_on:
      - mysql

volumes:
  db-data:
