version: '3.9'
services:
  api:
    build:
      target: development
    image: dev-api

  studio:
    build:
      target: studio
    container_name: prisma-studio
    image: studio
    env_file: .env
    expose:
      - '5555'
    ports:
      - 5555:5555
    volumes:
      - ./prisma:/app/prisma
    depends_on:
      - mysql
