version: '3.9'
services:
  api:
    build:
      target: development
    image: dev-api
    depends_on:
      - studio
      - mysql

  package:
    build:
      context: .
      target: base
    image: package

  studio:
    build:
      context: .
      target: studio
    container_name: prisma-studio
    image: studio
    env_file: .env
    expose:
      - '5555'
    ports:
      - 5555:5555
    volumes:
      - ./prisma:/app/prisma
